all:

sample1:
	nvcc -o sample1.exe sample1.cu
	./sample1.exe

sample2:
	nvcc -o sample2.exe sample2.cu
	./sample2.exe

sample3:
	nvcc -o sample3.exe sample3.cu
	./sample3.exe

sample4:
	nvcc -o sample4.exe sample4.cu
	./sample4.exe

clean:
	rm -rf *.o *.exe

.PHONY: all clean sample1 sample2 sample3 sample4

